name: C/C++ CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: [ master ]
    tags:
    - zopfli-1.*
  pull_request:
    branches: [ master ]
  schedule:
    # run every Wednesday at 0 AM UTC
    - cron: "0 0 * * 3"
  

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test

    steps:
    - uses: actions/checkout@v2
    - name: list files
      run: ls
    - name: make run
      run: make run
