name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test

    steps:
    - uses: actions/checkout@v2
    - name: list files
      run: ls
    - name: make run
      run: make run
